#!/bin/bash

# This script slices audio into separate files based on silent place in the audio file.

IN=$1
OUT=$(basename "$IN" .wav)%03d.wav

if [ -z "$IN" ]; then
    echo "It is necessary to have an audio clip for input."
    exit 1
fi

echo "Determining split points..." >& 2

ENDS=$(
    ffmpeg  -v warning -i "$IN" -af silencedetect=-65dB:d=0.3,ametadata=mode=print:file=-:key=lavfi.silence_start  -vn -sn -f wav -y /dev/null \
    | grep lavfi.silence_start= \
    | cut -f 2-2 -d = \

)

STARTS=$(
    ffmpeg  -v warning -i "$IN" -af silencedetect=-65dB:d=0.3,ametadata=mode=print:file=-:key=lavfi.silence_end  -vn -sn -f wav -y /dev/null \
    | grep lavfi.silence_end= \
    | cut -f 2-2 -d = \

)

IFS=$'\n' read -rd '' -a start_array <<<"$STARTS"
IFS=$'\n' read -rd '' -a end_array <<<"$ENDS"

start_array=('0.0' "${start_array[@]}")

echo
echo "Processing..."
echo

total=${#start_array[*]}
for (( j=0; j<=$(( $total -1 )); j++ ))
        do 
        s=${start_array[$j]}
        e=${end_array[$j]}
        echo -n "Start: $s "
        echo -n "End: $e "
        new_duration=`echo $e - $s | bc -l`
        echo "Duration= $new_duration"
        ffmpeg -y -ss $s -i "$IN" -t $new_duration -c copy -map 0 $(basename "$IN" .m4a)-$j.m4a
        done

echo "Audio has been split!"
