#!/bin/bash

FILENAME=${1?Error: no file given}
CD=()

if [[ "$FILENAME" =~ "countdown"  ]]; then
    CD+=("$FILENAME")
else
    echo "This file is not a Countdown."
fi
CD_NAME="${CD/HD.mov/}"
CD_HD="${CD_NAME}HD.mov"
CD_SD="${CD_NAME}SD.mov"
CD_CONVERT=($CD_HD $CD_SD)
open "$CD_HD"

read -p "Press enter after choosing the thumbnail frame." answer

CD_FOLDER="$PWD/../"$CD_NAME"Upload"
mkdir -p "$CD_FOLDER"

get_Thumb_Time() {

TIME=$(osascript <<-EOF

tell application "QuickTime Player"
		activate
		set thumbnailTime to current time of document 1
		close document 1
end tell

get thumbnailTime

EOF
    )
}

get_Thumb_Time $CD_HD

PNG=${CD_HD/mov}png
JPEG="$CD_FOLDER"/"${CD_HD/mov}jpg"

#OUTPUT THE PNG THUMB / CONVERT TO JPG / DELETE PNG
ffmpeg -loglevel quiet -y -ss $TIME -i $CD_HD -q:v 1 -vframes 1 -tune animation $PNG
sips -s format jpeg "$PNG" --out "$JPEG" && rm $PNG

for FILENAME in ${CD_CONVERT[@]}
do
    theFile="$CD_FOLDER"/"$FILENAME"
    # ffmpeg -y -i "$FILENAME" -c:v libx264 -pix_fmt yuv420p "$theFile"
    ffmpeg -y -i "$FILENAME" -c:v libx264 -x264-params "nal-hrd=cbr" -b:v 3M -minrate 3M -maxrate 3M -bufsize 5M -c:a aac -b:a 192k -pix_fmt yuv420p "$theFile"
    
done

open -R $theFile