#!/bin/bash

# This is a script for encoding Motion Retitles.

FILES=( "$@" )
if [ ${#FILES[@]} -eq 0 ]; then
    echo "Error: no files given"
    exit 1
fi

# Get the directory of the first file provided
FILE_DIR="$(dirname "${FILES[0]}")"
PARENT_DIR="$(dirname "$FILE_DIR")"
UPLOAD="$PARENT_DIR/Uploads"

HD=()
SD=()

# Create the Uploads directory if it doesn't exist
mkdir -p "$UPLOAD"

# Classify files into HD and SD based on their aspect ratio
for FILENAME in "${FILES[@]}"
do
    DAR=$(ffprobe -v error -select_streams v:0 -show_entries stream=display_aspect_ratio -of default=noprint_wrappers=1:nokey=1 "$FILENAME")
    if [[ "$DAR" =~ "4:3" ]]; then
        SD+=("$FILENAME")
    else
        HD+=("$FILENAME")
    fi
done

# Encode HD files
for HDFILES in "${HD[@]}"
do
    base_name="$(basename "$HDFILES" .mov)"
    theFile="$UPLOAD/$base_name.mp4"
    theMPEG="$UPLOAD/$base_name.mpg"
    
    ffmpeg -y -i "$HDFILES" -c:v libx264 -pix_fmt yuv420p "$theFile" \
        -vf "scale=iw*0.66666667:ih*0.66666667" -c:v mpeg1video -b:v 6500k "$theMPEG"
done

# Encode SD files
for SDFILES in "${SD[@]}"
do
    base_name="$(basename "$SDFILES" .mov)"
    theFile="$UPLOAD/$base_name.mp4"
    theMPEG="$UPLOAD/$base_name.mpg"
    
    ffmpeg -y -i "$SDFILES" -c:v libx264 -pix_fmt yuv420p "$theFile" \
        -vf "scale=640:480" -b:v 4500k -minrate 4500k -maxrate 8500k -bufsize 15000k "$theMPEG"
done

# Open the enclosing folder
if [[ -n "$UPLOAD" ]]; then
    open -R "$UPLOAD"
fi
