#!/bin/bash

IN=( "$@" ) #Take in a group of files
default_tag=$"/Users/trentarmstrong/Desktop/_Current_Igniter_Projects/1-Mini_Movie_Tag/Assets/Igniter-Tag.mov"
read -p "Logo tag to use [Default is Igniter Logo] > " TAG #Ask if there is a different logo tag to use
TAG=${TAG:-$default_tag}

OUTPUT="../Tagged_Movies""/$(basename "$1" .mp4)-tagged.mov"

#Build File List
LINE=$(echo file \'$IN\' file \'$TAG\')

# define the movie array  
movie=($1)   

#define end card array  
endcard=($TAG)  

# Use for loop  
# get total subscripts in an array  
total=${#movie[*]}  

for (( i=0; i<=$(( $total -1 )); i++ ))  
    do  
        echo
        echo "Processing ..." ${movie[0]}
        # -loglevel quiet
        ffmpeg -i ${movie[0]}  -i ${endcard[0]} -y -filter_complex '[0:v]scale=1920:1080,setsar=1[in1];[1:v]scale=1920:1080,setsar=1[in2];[in1][0:a:0][in2][1:a:0]concat=n=2:v=1:a=1 [v][a]' -map '[v]' -map '[a]' -c:v libx264 -pix_fmt yuv420p $OUTPUT
    done

echo
echo "Processing Complete!"
echo