#!/bin/bash

IN=( "$@" )
THE_PATH=$"/Users/trentarmstrong/Desktop/_Current_Igniter_Projects/1-Mini_Movie_Tag/Assets"
IG_TAG=$"Igniter-Tag.mov"
WT_TAG=$"Worship_Together_Tag_HD.mov"
WTK_TAG=$"WT_Kids_Tag_HD.mov"
default_tag="$THE_PATH/$IG_TAG"

# read -p "Logo tag to use [Default is Igniter Logo] > " TAG

PS3="Enter a number: "

select logo_tag in $IG_TAG $WT_TAG $WTK_TAG
do
    TAG="$THE_PATH/$logo_tag"
    break
done

echo "$TAG"