#!/bin/bash

CWD=$PWD
FILES=*.*             
FOLDERS=()
MAKE=()
FAIL=()
PASS=()
HD=()
HD_FIN=()
SD=()
SD_FIN=()
UW_HD=()
UW_SD=()

# POPULATE HD ARRAY
for FILE in $FILES
do
        if [[ "$FILE" =~ "HD"  ]]; then
                HD+=("$FILE")
        fi
done

# POPULATE SD ARRAY
for FILE in $FILES
do
        if [[ "$FILE" =~ "SD"  ]]; then
                SD+=("$FILE")
        fi
done
i=0
# POPULATE UW_HD ARRAY
for FILE in ${HD[@]}
do
        if [[ "$FILE" =~ "UW"  ]]; then
                UW_HD+=("$FILE")
        else
                HD_FIN+=("$FILE")
        fi
done

# POPULATE UW_SD ARRAY
for FILE in ${SD[@]}
do
        if [[ "$FILE" =~ "UW"  ]]; then
                UW_SD+=("$FILE")
        else
                SD_FIN+=("$FILE")
        fi
done

for FILE in ${SD_FIN[@]}
do
SIZE=$(ffprobe -v fatal -select_streams v:0 -show_entries stream=height,width -of csv=s=x:p=0 "$FILE")
        if [[ "$SIZE" =~ "1440x1080"  ]]; then
                PASS+=("$FILE")
        else
                FAIL+=("$FILE")
        fi
done

for FILE in ${HD_FIN[@]}
do
SIZE=$(ffprobe -v fatal -select_streams v:0 -show_entries stream=height,width -of csv=s=x:p=0 "$FILE")
        if [[ "$SIZE" =~ "1920x1080"  ]]; then
                PASS+=("$FILE")
        else
                FAIL+=("$FILE")
        fi
done



for FILE in ${UW_SD[@]}
do
SIZE=$(ffprobe -v fatal -select_streams v:0 -show_entries stream=height,width -of csv=s=x:p=0 "$FILE")
        if [[ "$SIZE" =~ "1920x480"  ]]; then
                PASS+=("$FILE")
        else
                FAIL+=("$FILE")
        fi
done


for FILE in ${UW_HD[@]}
do
SIZE=$(ffprobe -v fatal -select_streams v:0 -show_entries stream=height,width -of csv=s=x:p=0 "$FILE")
        if [[ "$SIZE" =~ "3840x720"  ]]; then
                PASS+=("$FILE")
        else
                FAIL+=("$FILE")
        fi
done

pList() {
arr=${@}
for ITEM in $arr;
do
echo $ITEM
done
}

# echo "PASSED"
# pList ${PASS[@]}
# echo "-----------------"

# echo "FAILED"
# pList ${FAIL[@]}
# echo
# echo

# ADD FOLDER NAMES TO ARRAY
for NAME in ${PASS[@]}
do
        if [[ "$NAME" =~ "_HD.jpg" ]]; then
                FOLDERS+=($NAME)
        fi
done

# CLEAN UP FOLDERS LIST
for ITEM in ${FOLDERS[@]}
do
        if ! [[ "$ITEM" =~ "UW" ]]; then
                BASENAME="${ITEM/_HD.jpg/}"
                MAKE+=($BASENAME)
        fi
done

# CREATE MASTER FOLDERS
for d in ${MAKE[@]}
do
        mkdir $d
done

# MATCH FILES AND PUT THEM IN FOLDERS
for x in ${MAKE[@]}
do
        for ITEMS in ${PASS[@]}
        do
                if [[ "$ITEMS" =~ "$x" ]]; then
                        mv $ITEMS $x
                fi
        done
done
