#!/bin/bash

get_Thumb_Time() {

TIME=$(osascript <<-EOF

tell application "QuickTime Player"
		activate
		set thumbnailTime to current time of document 1
end tell

tell application "Chrome" to activate

get thumbnailTime

EOF
    )
}

get_Thumb_Time

echo $TIME | pbcopy