#!/bin/bash

#FILENAME=${1?Error: no file given}

FILES=( "$@" )

for FILENAME in ${FILES[@]}
do
    theFile="$(basename "$FILENAME" _HD.mov)_SD.mov"
    ffmpeg -y -i "$FILENAME" -filter:v crop=in_w/\(4/3\):in_h -c:v prores -profile:v 2 -pix_fmt yuv420p "$theFile"
done

# echo
# echo "-----------------------------------------------------"
# echo "The file is: " "$FILENAME"
# echo "The directory is:" "$PWD"
# echo "The Uploads folder is: " "$UPLOAD"
# echo "-----------------------------------------------------"
# echo

open -R $theFile
