#!/bin/bash

THEFILES=( "$@" )

#Open the first file in QuickTime and pasue for USER to choose thumbnail time
FIRSTFILE="${THEFILES[0]}" 
open "$FIRSTFILE"

read -p "Press enter after choosing the thumbnail frame." answer

get_Thumb_Time() {

theFile=$1

TIME=$(osascript <<-EOF

tell application "QuickTime Player"
		activate
		set thumbnailTime to current time of document 1
		close document 1
end tell

get thumbnailTime

EOF
)

}

get_Thumb_Time $FIRSTFILE

for FILE in "${THEFILES[@]}"
 do
 
 	PNG=${FILE/mov}png
 	JPEG=${FILE/mov}jpg

	# OUTPUT THE PNG THUMB / CONVERT TO JPG / DELETE PNG
	ffmpeg -loglevel quiet -y -ss $TIME -i $FILE -q:v 1 -vframes 1 -tune animation $PNG
	sips -s format jpeg "$PNG" --out "$JPEG" && rm $PNG
done