#!/bin/bash

IN=( "$@" )

default_tag=$"/Users/trentarmstrong/Desktop/_Current_Igniter_Projects/1-Mini_Movie_Tag/Assets/U"

read -p "Logo tag to use [Default is Worship Together Logo] > " TAG

TAG=${TAG:-$default_tag}
NO_AUDIO=()
WRONG_SIZE=()

echo
echo "Checking for audio..." 

#Build File List
LINE=$(echo file \'$IN\' file \'$TAG\')

# define the movie array  

inputs=($IN)   

#define end card array  

endcard=($TAG)  

# Use for loop  
# get total subscripts in an array  

for FILE in ${IN[@]}
do
SIZE=$(ffprobe -v fatal -select_streams a:0 -show_entries stream=codec_name -of csv=s=x:p=0 "$FILE")
# echo $SIZE
        if [[ "$SIZE" != ""  ]]; then
                
                movie+=("$FILE")
        else
                NO_AUDIO+=("$FILE")
        fi
done

total=${#movie[*]}  

echo "CONVERTING $total FILES"
echo

for (( i=0; i<=$(( $total -1 )); i++ ))  
    do  
        OUTPUT="../_Tagged""/$(basename "${movie[i]}" .mov)-tagged.mov"
        echo "Processing ..." ${movie[i]}
        # -loglevel quiet
        ffmpeg -y -i ${movie[i]} -i ${endcard} -dn -filter_complex '[0:v]scale=1920:1080,setsar=1[in1];[1:v]scale=1920:1080,setsar=1[in2];[in1][0:a:0][in2][1:a:0]concat=n=2:v=1:a=1 [v][a]' -map '[v]' -map '[a]' -c:v libx264 -pix_fmt yuv420p $OUTPUT
        echo "Complete:" $OUTPUT
        # ffprobe -v error -of flat=s_ -select_streams 1 -show_entries stream=duration -of default=noprint_wrappers=1:nokey=1 ${movie[0]}
    done

echo
echo "Processing Complete!"
echo

echo "FAILED: "${NO_AUDIO[@]}
echo

# ALERT CODE
# osascript -e 'tell app "System Events" to display dialog "FAILED: ${NO_AUDIO[@]}"'

# FFPROBE Check for audio stream
# ffprobe -v error -of flat=s_ -select_streams 1 -show_entries stream=duration -of default=noprint_wrappers=1:nokey=1